<<<<<<< HEAD
#!/bin/bash
#
# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
=======
# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
>>>>>>> 4aa29108e5fa51c58a39be5e062856a9fad9cee1
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
<<<<<<< HEAD
#

set -e
=======

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files

OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l device-proprietary-blobs.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' device-proprietary-blobs.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' ../$DEVICE/device-proprietary-blobs.txt`; do
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
      # Split the file from the destination (format is "file[:destination]")
  OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
  FILE=${PARSING_ARRAY[0]}
  DEST=${PARSING_ARRAY[1]}
  if [ -n "$DEST" ]; then
    FILE=$DEST
  fi
  if [ -f ../../../$OUTDIR/proprietary/$FILE ]; then
      echo "	$OUTDIR/proprietary/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
  else
      echo "ERR: file not found: $OUTDIR/proprietary/$FILE"
  fi
done

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
EOF
>>>>>>> 4aa29108e5fa51c58a39be5e062856a9fad9cee1

# Load extract_utils and do some sanity checks
MY_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$MY_DIR" ]]; then MY_DIR="$PWD"; fi

<<<<<<< HEAD
CM_ROOT="$MY_DIR"/../../..

HELPER="$CM_ROOT"/vendor/cm/build/tools/extract_utils.sh
if [ ! -f "$HELPER" ]; then
    echo "Unable to find helper script at $HELPER"
    exit 1
fi
. "$HELPER"
=======
(cat << EOF) > $MAKEFILE
>>>>>>> 4aa29108e5fa51c58a39be5e062856a9fad9cee1

# Initialize the helper for common device
setup_vendor "$DEVICE_COMMON" "$VENDOR" "$CM_ROOT" true

# Copyright headers and common guards
write_headers "zerofltedv zerofltemtr zerofltespr zerofltetmo zerofltexx zeroltetmo zeroltexx"

<<<<<<< HEAD
write_makefiles "$MY_DIR"/common-proprietary-blobs.txt

write_footers
=======
(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
EOF

(cat << EOF) > ../../../$OUTDIR/Android.mk
>>>>>>> 4aa29108e5fa51c58a39be5e062856a9fad9cee1

# Reinitialize the helper for device
setup_vendor "$DEVICE" "$VENDOR" "$CM_ROOT"

<<<<<<< HEAD
# Copyright headers and guards
write_headers

write_makefiles "$MY_DIR"/../$DEVICE/device-proprietary-blobs.txt

write_footers
=======
EOF
>>>>>>> 4aa29108e5fa51c58a39be5e062856a9fad9cee1
